### ISSUE TITLE
Use the same time step for all permamodel models

### ISSUE THREAD

**Issue by mdpiper** [permamodel/permamodel#36]
KuModel and FrostNumberModel use a time step of one year, while CRUAKTemp uses a time step of one day. We should use the same step size and units for all models.

Side note: As an alternative, I could write wrapper code in WMT to make CRUAKTemp use a one-year time step. This would require no changes to the permamodel code.

**Comment by Elchin** [comment]
I think, the input data for both model has to averaged yearly first, which could be done internally inside the model. If I remember correctly Frost model accepts monthly data as well, the same is true for Ku.

**Comment by sc0tts** [comment]
The answer here depends on how we want the physics models (Frostnumber, Ku)
to interact with the data "model" (cruAKtemp).

If we want a one-year timestep, then cruAKtemp should provide 12 values
(monthly averages) at each location as its output.  The physics models
would then take those and do what they want (average; fit a cosine wave) to
those 12 values.

Alternatively, a least-common timestep could be chosen and all models would
give/take information at that timestep.  That was the reason for choosing
"1 day" because only with a "day" timestep do you have a non-changing
timestep from which you can derive a precise date.  (E.g., a "month"
timestep could be used with this specific combination of models, but a
"month" is not a fixed unit of time...its duration depends on the
month/year.)

Or...we could allow a "month" timestep, knowing that all models have to
"understand" it.

The FrostnumberGeo code (not yet ingested) expects WMT to use cruAKtemp to
update its current "bottom air temperature" array every day, but it doesn't
update its internal "air_temp_minimum" and "air_temp_maximum" arrays until
the relevant dates have been reached.

Summary:  deciding on a timestep makes us decide what information gets
passed and which codes do what:

   - Day time step:  Each model is responsible for noting when it has to
   update its internal arrays based on the newly set information.  E.g.
   accumulate running total and total days sums until a new Year has
   occurred.  Data "model" updates each other's models arrays at every
   timestep, perhaps could check to see if that information has changed.
   - Month timestep: As per Day time step, each component needs to keep
   track internally of sum/num until it reaches an averaging point (e.g. a
   year).  Timestep is understood to have unequal durations
   - Year timestep: Instead of a single temperature field, the Data
   Component needs to send it's yearly information all at once.  In this case,
   that will be 12 values for each grid location

All are workable.  Just a matter of deciding.

-Scott

**Comment by sc0tts** [comment]
Another thought about model time:

One of the differences between a normal model and a "data" model (like cruAKtemp) is that while physical models can only march forward in time -- and record values from the present for future use, data models can know the future.

That means that in some sense, they are not strictly limited to what is known at the current timestep.  They could do look-forward operations -- e.g. spline interpolations -- or look-back operations -- e.g. yield the average values from the last <some number> of months.

I don't think the current WMT architecture is really set up to permit that, because there isn't a Standard Name for <what-this-value-was-at-some-point-in-the-past>, but it's something we should be aware of.

**Comment by sc0tts** [comment]
Let me see if I understand the timestep correctly:

Ku, KuGeo, Frostnumber, and FrostnumberGeo will all use a timestep of one year.  They will each require one set of inputs and yield one set of outputs per calendar year.  Their "timestep 0" will correspond to their "start year."

Because cruAKtemp wraps monthly sets of data, it has information about each month.  But, for compatibility with the other models, it will have the ability to increment by year.  

cruAKtemp currently outputs 3 sets of fields: (1) the current temperature field, (2) each of the last 12 months' temperature fields, and (3) the average field of the last 12 months.

I suggest that the interpretation of the "day" be "December 15th" of the model year.  That way, the 12-month average refers to a calendar year, and each of the monthly fields are from the same calendar year.

**Comment by mdpiper** [comment]
All PMT models now use a yearly time step. Closing.
